@startuml sequence
actor       Tester        as tester
participant "Katalon Studio\nedit Profile" as kspf
participant "Katalon Studio\nrun Test Case" as kstc
participant "Katalon Studio\nrun Test Suite" as ksts
database    "./Profiles/\ndefault.glbl" as glbl
database    "./Libs/internal/\nGlobalVariable.groovy" as gvgr
participant "Test Case TC1" as TC1
participant "Test Case TC2" as TC2

== step 1 ==
tester -> kspf : edit default profile,\nadd GlobalVariable.foo
kspf   -> glbl : serialize the profile into XML file
kspf   -> gvgr : generate Groovy source code
tester -> kstc : run Test Case TC1
== step 2 ==
@enduml
